AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.sayHello
      Runtime: nodejs14.x
      CodeUri: ./hello
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  MyApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"